# Actividad Individual Data Wrangling - PARTE A

**Angel Irwin Briseño Fierro A01796844**

En esta practica se realizara el EDA y proceso de limpieza de los datasets provistos "room-occupancy-estimation", original y modificado, con la finalidad de obtener una comparacion tal que evidencie la influencia de estos procesos en los datos y que pueden repercutir en procesos mas adelante en el desarrollo de modelos de ML.

## Dataset original

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as  plt
import seaborn as sns
import json

In [ ]:
with open(r'D:\Master\MLops\A03_Data_Cleaning_EDA\room-occupancy-estimation\metadata.json', 'r', encoding='utf-8') as file:
    data = json.load(file)

print(data)

{'name': 'Room Occupancy Estimation', 'slug': 'room-occupancy-estimation', 'page': 'https://archive.ics.uci.edu/dataset/864/room+occupancy+estimation', 'source': 'web', 'downloaded': ['data/room-occupancy-estimation/original/room+occupancy+estimation.zip'], 'original_csv': 'data/room-occupancy-estimation/original.csv', 'modified_csv': 'data/room-occupancy-estimation/modified.csv', 'shape_original': [10129, 19], 'shape_modified': [10331, 20], 'hash_original_csv': 'b1233661bf4ef0bf3aefca4714693e3b5b0b47288e899f3026be23976b0d3e6e', 'hash_modified_csv': '53d80813eda203f3acfa9f0bbfeea28abe181c43f34fd15efe774e67d3355275', 'seed': 42, 'rates': {'dup_rate': 0.02, 'nan_rate': 0.01, 'outlier_rate': 0.01, 'bad_token_rate': 0.005, 'obj_noise_rate': 0.05, 'add_mixed_type': True}}

In [ ]:
ogDf = pd.read_csv(r'D:\Master\MLops\A03_Data_Cleaning_EDA\room-occupancy-estimation\original.csv')
ogDf.head()

,Date,Time,S1_Temp,S2_Temp,S3_Temp,S4_Temp,S1_Light,S2_Light,S3_Light,S4_Light,S1_Sound,S2_Sound,S3_Sound,S4_Sound,S5_CO2,S5_CO2_Slope,S6_PIR,S7_PIR,Room_Occupancy_Count
0,2017/12/22,10:49:41,24.94,24.75,24.56,25.38,121,34,53,40,0.08,0.19,0.06,0.06,390,0.769231,0,0,1
1,2017/12/22,10:50:12,24.94,24.75,24.56,25.44,121,33,53,40,0.93,0.05,0.06,0.06,390,0.646154,0,0,1
2,2017/12/22,10:50:42,25.00,24.75,24.50,25.44,121,34,53,40,0.43,0.11,0.08,0.06,390,0.519231,0,0,1
3,2017/12/22,10:51:13,25.00,24.75,24.56,25.44,121,34,53,40,0.41,0.10,0.10,0.09,390,0.388462,0,0,1
4,2017/12/22,10:51:44,25.00,24.75,24.56,25.44,121,34,54,40,0.18,0.06,0.06,0.06,390,0.253846,0,0,1

## Dataset modificado

In [5]:
ogDf = pd.read_csv(r'D:\Master\MLops\A03_Data_Cleaning_EDA\room-occupancy-estimation\modified.csv')
ogDf.head()

,Date,Time,S1_Temp,S2_Temp,S3_Temp,S4_Temp,S1_Light,S2_Light,S3_Light,S4_Light,S1_Sound,S2_Sound,S3_Sound,S4_Sound,S5_CO2,S5_CO2_Slope,S6_PIR,S7_PIR,Room_Occupancy_Count,mixed_type_col
0,2017/12/22,10:49:41,24.94,345.75,24.56,25.38,121.0,34.0,53.0,40.0,0.08,0.19,0.06,0.06,390.0,0.769230769231,0.0,0.0,1.0,599
1,2017/12/22,10:50:12,24.94,24.75,24.56,25.44,121.0,33.0,53.0,40.0,0.93,0.05,0.06,0.06,390.0,0.646153846154,0.0,0.0,1.0,NaN
2,2017/12/22,10:50:42,25.0,24.75,24.5,25.44,121.0,34.0,53.0,40.0,0.43,0.11,0.08,0.06,390.0,0.519230769231,0.0,0.0,1.0,unknown
3,2017/12/22,10:51:13,25.0,24.75,24.56,25.44,121.0,34.0,53.0,40.0,0.41,0.1,0.1,0.09,390.0,0.388461538462,0.0,0.0,1.0,584
4,2017/12/22,10:51:44,25.0,24.75,24.56,25.44,121.0,34.0,54.0,40.0,0.18,0.06,0.06,0.06,390.0,0.253846153846,0.0,0.0,1.0,bad